### ISSUE TITLE
Location of self contained example?

### ISSUE THREAD

**Issue by coreyoconnor** [scalaprops/scalaprops#37]
The only self-contained example (one that doesn't reference laws in the scalaz project) is visible for a less than a second in the gif. An example that does not require looking into scalaz's source code would be helpful for quick-starting use of scalaprops.

**Comment by coreyoconnor** [comment]
After a bit of searching I found:

* https://github.com/scalaprops/scalaprops-examples

which satisfies the requirement. The only thing missing, then: a link to the examples from the readme/docs.

**Comment by xuwei-k** [comment]
pull request welcome :)

**Comment by coreyoconnor** [comment]
Happy to handle this! It's in my queue. Which is long :(
