### ISSUE TITLE
Example test in sample project

### ISSUE THREAD

**Issue by non** [scalaprops/scalaprops#9]
Would it be possible to set up the *scalazlaws* subproject so that running `test` would check a few of the laws? Right now it's not totally clear how to hook it all together.

**Comment by xuwei-k** [comment]
Is this helpful for you? 
https://github.com/scalaprops/scalaprops/blob/201b7890bc6e177f1/scalaprops/src/test/scala/scalaprops/ListTest.scala

You mean I should add some scalazlaws examples to [scalaprops-exmaples](https://github.com/scalaprops/scalaprops-examples) project?

**Comment by non** [comment]
Oh, I understand now. I missed that the tests were in the scalaprops project itself. Thanks!
